### ISSUE TITLE
Null Authentication Object caused 500 Server Error for HTTP GET

### ISSUE THREAD

**Issue by kzmuhia** [soasada/kotlin-coroutines-webflux-security#1]
Hi Nicholas,

Thanks for this very useful repo.

Not sure it is an issue but I noticed that whenever there is a null authentication object then the request returns a 500 as opposed to 401 probably due to an uncaught exception within the authorization Manager interface

org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:379)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:

**Comment by soasada** [comment]
Hi Kenneth,

First of all, thanks for your submission, I will try to replicate this error and fix it ASAP. 

Good catch!

**Comment by kzmuhia** [comment]
Hi Nicholas,

Thanks, it seems to get resolved when checking if we have an valid authentication within the Security Context.

**Comment by soasada** [comment]
I just looked at the problem and it seems to be a DEBUG message and nothing to worry about, also I cannot reproduce.
From the Spring Security docs:

> This is a another debug level message which occurs the first time an anonymous user attempts to access a protected resource, but when you do not have an `AnonymousAuthenticationFilter` in your filter chain configuration.

[Spring Security docs](https://docs.spring.io/spring-security/site/docs/5.3.4.RELEASE/reference/html5/#auth-exception-credentials-not-found)

Could you provide to me the steps to reproduce this error? If you do so, I could make a integration test a fix it a make a new release.

**Comment by kzmuhia** [comment]
Hi Nicholas,

I logged in to get a token

SIG-KILLED the process

Started it and tried to use the same token and got a 500.

When I added 
val auth = SecurityContextHolder.getContext()?.authentication?: return@mono notAuthorized

inside the JWTReactiveAuthorizationManager interface then I got the correct 401 response

**Comment by soasada** [comment]
Ok, now I have everything I need, thanks man!

**Comment by soasada** [comment]
Hi Kenneth,

I follow your steps and I was not able to reproduce the issue. I put here the steps that I follow:

1. Login with `user@example.com` and `userPassword` and obtained a token.
2. I stop the application.
3. Run again.
4. Try to consume a protected resource.
5. I get the information from the protected resource.

I think that this is the expected behavior and should be, JWT usually is used to protected APIs separated from the clients and this is by nature stateless (which means, no session storage in the server), the session is the JWT itself that is interchanged between clients and the server.

Are you getting the error with the code of this repository?

**Comment by kzmuhia** [comment]
Hi Nicholas,

You are right I am actually getting that exception when I attempted to use @PreAuthorize annotation on some URLs.
